site_name: "devex-techdocs-experiment"
site_description: "A guide to mobile application development for the Government of the Province of British Columbia"
repo_url: https://github.com/bcgov/developer-experience-techdocs-experimental
edit_uri: edit/main/docs/

plugins:
  - techdocs-core